---
title: "Rank genes"
output: html_notebook
description: cardiogenesis
---


```{r}
library(SingleCellExperiment)
library(corgi)

lescroart <- readRDS(file = "sce_rds_files/lescroart.Rds")

lescroart <- lescroart[(rowMeans(counts(lescroart)==0)<0.95), ] 

lescroart <- lescroart[ , (colMeans(counts(lescroart)==0)<0.95)]
table(lescroart$Study)
lesc <- lescroart[ , lescroart$Study != "wj"]
scia <- lescroart[ , lescroart$Study == "wj"]

```

```{r}
gene_rankings <- list()
gene_rankings[["HDG(Lescroart)"]] <- HDG_ranking(lesc)
gene_rankings[["HDG(Scialdone)"]] <- HDG_ranking(scia)
```


```{r}
gl <- Seurat_CCA_GeneLoading(counts(lesc), counts(scia))
gene_rankings[["CCA-GL"]] <- names(sort(rowSums(gl^2),decreasing = T))
```

```{r}
corgi_out <- readRDS(file = "other_rds_files/corgi_out.Rds")


corgi_score <- corgi_out[,1:3]/corgi_out[,"num.times.sampled"]

gene_rankings[["CORGI"]] <- names(sort(corgi_score[,"principal_curve"]))

saveRDS(gene_rankings, file = "other_rds_files/gene_rankings.Rds")
```